# Generated by Django 5.2 on 2025-05-03 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cancer_classifier', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='conversation_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
