# Generated by Django 5.2 on 2025-05-14 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cancer_classifier', '0004_imageupload'),
    ]

    operations = [
        migrations.CreateModel(
            name='SkinCondition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('condition_type', models.CharField(choices=[('benign', 'Benign'), ('malignant', 'Malignant'), ('precancerous', 'Precancerous')], max_length=20)),
                ('image', models.ImageField(blank=True, null=True, upload_to='skin_conditions/')),
                ('detected_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
