# Generated by Django 5.2 on 2025-05-14 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cancer_classifier', '0005_skincondition'),
    ]

    operations = [
        migrations.CreateModel(
            name='HealthTopic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('category', models.CharField(choices=[('cancer', 'Cancer'), ('nutrition', 'Nutrition'), ('mental_health', 'Mental Health'), ('fitness', 'Fitness'), ('skin_health', 'Skin Health'), ('general', 'General')], max_length=50)),
                ('image', models.ImageField(blank=True, null=True, upload_to='health_topics/')),
                ('published_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
