# Generated by Django 5.2 on 2025-05-14 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cancer_classifier', '0006_healthtopic'),
    ]

    operations = [
        migrations.CreateModel(
            name='HealthArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('category', models.CharField(choices=[('cancer', 'Cancer'), ('mental_health', 'Mental Health'), ('fitness', 'Fitness'), ('nutrition', 'Nutrition'), ('other', 'Other')], max_length=50)),
                ('content', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='health_articles/')),
                ('published_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
